apiVersion: apps/v1
kind: Deployment
metadata:
  name: laseris-website-api
  namespace: laseris-website
  labels:
    app: laseris-website-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: laseris-website-api
  template:
    metadata:
      labels:
        app: laseris-website-api
    spec:
      imagePullSecrets:
        - name: github-registry
      containers:
        - name: laseris-website-api
          image: ghcr.io/ptrrr/laseris-api:sha-d6c366d
          ports:
            - containerPort: 3000
          env:
            - name: DATABASE_URI
              valueFrom:
                secretKeyRef:
                  name: laseris-website-secrets
                  key: database-uri
            - name: PAYLOAD_SECRET
              valueFrom:
                secretKeyRef:
                  name: laseris-website-secrets
                  key: payload-secret
            - name: S3_BUCKET
              valueFrom:
                secretKeyRef:
                  name: laseris-website-secrets
                  key: s3-bucket
            - name: S3_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: laseris-website-secrets
                  key: s3-endpoint
            - name: S3_REGION
              valueFrom:
                secretKeyRef:
                  name: laseris-website-secrets
                  key: s3-region
            - name: S3_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: laseris-website-secrets
                  key: s3-access-key
            - name: S3_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: laseris-website-secrets
                  key: s3-secret-key
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: laseris-website-secrets
                  key: openai-api-key
            - name: NODE_ENV
              value: "production"
            - name: PORT
              value: "3000"

          resources:
            limits:
              cpu: 400m
              memory: 512Mi
            requests:
              cpu: 200m
              memory: 512Mi
          livenessProbe:
            httpGet:
              path: /api/health
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /api/health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: laseris-website-api-service
  namespace: laseris-website
  labels:
    app: laseris-website-api
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
  selector:
    app: laseris-website-api
