apiVersion: batch/v1
kind: CronJob
metadata:
  name: postgres-backup-s3
  namespace: laseris-website
  labels:
    app: postgres-backup-s3
spec:
  schedule: "0 2 * * *" # Daily at 2 AM
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          imagePullSecrets:
            - name: github-registry
          containers:
            - name: dbkp-backup
              image: ghcr.io/bloccooo/dbkp/dbkp:latest
              command:
                - /bin/sh
                - -c
                - |
                  dbkp backup \
                    --database-type postgresql \
                    --database "$DB_NAME" \
                    --host "$DB_HOST" \
                    --port "$DB_PORT" \
                    --username "$DB_USER" \
                    --password "$DB_PASSWORD" \
                    --storage-type s3 \
                    --bucket "$S3_BUCKET" \
                    --endpoint "$S3_ENDPOINT" \
                    --access-key "$S3_ACCESS_KEY" \
                    --secret-key "$S3_SECRET_KEY" \
                    --region "$S3_REGION" \
                    --location invoices-backups \
                    --retention "${RETENTION:-30d}"
              env:
                - name: DB_HOST
                  value: "postgres-service"
                - name: DB_USER
                  valueFrom:
                    secretKeyRef:
                      name: laseris-website-secrets
                      key: postgres-user
                - name: DB_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: laseris-website-secrets
                      key: postgres-password
                - name: DB_NAME
                  valueFrom:
                    secretKeyRef:
                      name: laseris-website-secrets
                      key: postgres-db
                - name: DB_PORT
                  valueFrom:
                    secretKeyRef:
                      name: laseris-website-secrets
                      key: postgres-port
                - name: S3_BUCKET
                  valueFrom:
                    secretKeyRef:
                      name: laseris-website-secrets
                      key: db-backup-s3-bucket
                - name: S3_ENDPOINT
                  valueFrom:
                    secretKeyRef:
                      name: laseris-website-secrets
                      key: s3-endpoint
                - name: S3_ACCESS_KEY
                  valueFrom:
                    secretKeyRef:
                      name: laseris-website-secrets
                      key: s3-access-key
                - name: S3_SECRET_KEY
                  valueFrom:
                    secretKeyRef:
                      name: laseris-website-secrets
                      key: s3-secret-key
                - name: S3_REGION
                  valueFrom:
                    secretKeyRef:
                      name: laseris-website-secrets
                      key: s3-region
                - name: RETENTION
                  value: "30d"
              resources:
                requests:
                  memory: "256Mi"
                  cpu: "50m"
                limits:
                  memory: "512Mi"
                  cpu: "200m"
              volumeMounts:
                - name: dbkp-cache
                  mountPath: /home/dbkp/.cache
          volumes:
            - name: dbkp-cache
              persistentVolumeClaim:
                claimName: dbkp-cache-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dbkp-cache-pvc
  namespace: laseris-website
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
