apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc-laseris-website
  namespace: laseris-website
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
